services:
  cryptpad:
    image: "cryptpad/cryptpad:latest"
    container_name: cryptpad
    restart: unless-stopped
    security_opt: 
      - no-new-privileges:true    
    networks:
      proxy:
    environment:
      - CPAD_MAIN_DOMAIN=https://cryptpad.homelab.ru
      - CPAD_SANDBOX_DOMAIN=https://sandbox-cryptpad.homelab.ru
      - CPAD_CONF=/cryptpad/config/config.js
      - CPAD_INSTALL_ONLYOFFICE=yes
    volumes:
      - /home/alex/docker/cryptpad/blob:/cryptpad/blob
      - /home/alex/docker/cryptpad/block:/cryptpad/block
      - /home/alex/docker/cryptpad/customize:/cryptpad/customize
      - /home/alex/docker/cryptpad/data:/cryptpad/data
      - /home/alex/docker/cryptpad/datastore:/cryptpad/datastore
      - /home/alex/docker/cryptpad/onlyoffice-dist:/cryptpad/www/common/onlyoffice/dist
      - /home/alex/docker/cryptpad/onlyoffice-conf:/cryptpad/onlyoffice-conf
#      - /home/alex/docker/cryptpad/config.js:/cryptpad/config/config.js
    labels: 
      - "traefik.enable=true" 

      - "traefik.http.routers.cryptpad.entrypoints=https" 
      - "traefik.http.routers.cryptpad.rule=Host(`cryptpad.homelab.ru`)"  
      - "traefik.http.routers.cryptpad.tls=true" 
      - "traefik.http.routers.cryptpad.middlewares=security-headers@file"
      - "traefik.http.routers.cryptpad.service=cryptpad"
      - "traefik.http.services.cryptpad.loadbalancer.server.port=3000"

      - "traefik.http.routers.cryptpad-sandbox.entrypoints=https"
      - "traefik.http.routers.cryptpad-sandbox.rule=Host(`sandbox-cryptpad.homelab.ru`)"
      - "traefik.http.routers.cryptpad-sandbox.tls=true"
      - "traefik.http.routers.cryptpad-sandbox.middlewares=security-headers@file"
      - "traefik.http.routers.cryptpad-sandbox.service=cryptpad"

      - "traefik.http.routers.cryptpad-ws.entrypoints=https" 
      - "traefik.http.routers.cryptpad-ws.rule=Host(`cryptpad.homelab.ru`) && PathPrefix(`/cryptpad_websocket`)"  
      - "traefik.http.routers.cryptpad-ws.tls=true" 
      - "traefik.http.routers.cryptpad-ws.middlewares=security-headers@file"
      - "traefik.http.services.cryptpad-ws.loadbalancer.server.port=3003"
      - "traefik.http.routers.cryptpad-ws.priority=100"
      - "traefik.http.routers.cryptpad-ws.service=cryptpad-ws"
      
      - "traefik.http.routers.cryptpad-ws-sandbox.entrypoints=https" 
      - "traefik.http.routers.cryptpad-ws-sandbox.rule=Host(`sandbox-cryptpad.homelab.ru`) && PathPrefix(`/cryptpad_websocket`)"  
      - "traefik.http.routers.cryptpad-ws-sandbox.tls=true" 
      - "traefik.http.routers.cryptpad-ws-sandbox.middlewares=security-headers@file"
      - "traefik.http.routers.cryptpad-ws-sandbox.priority=100"
      - "traefik.http.routers.cryptpad-ws-sandbox.service=cryptpad-ws"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

networks:
  proxy:
    name: proxy 
    external: true
