services:
  glances:
    # See all images tags here: https://hub.docker.com/r/nicolargo/glances/tags
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: "host"
    networks:
      proxy:
    read_only: true
    privileged: false
    volumes:
      - "/:/rootfs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
      - "/etc/os-release:/etc/os-release:ro"
    environment:
      - GLANCES_OPT=-C /glances/conf/glances.conf -w --enable-mcp --enable-plugin smart
      - TZ=Europe/Moscow
    security_opt: 
      - no-new-privileges:true
    tmpfs:
      - /tmp
    labels: 
      - "traefik.enable=true" # Enable Traefik on this service
      - "traefik.http.routers.glances.entrypoints=https" # Secure entrypoint for HTTPS
      - "traefik.http.routers.glances.rule=Host(`glances.homelab.ru`)"  # Host rule for secure routing
      - "traefik.http.routers.glances.tls=true" # Enable TLS for secure connection
      - "traefik.http.routers.glances.middlewares=security-headers@file,authelia@docker"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
networks:
  proxy:
    name: proxy 
    external: true
